# <span style="color:green;">NumPy 02</span>

<span style="color:red;">Creating Numpy Arrays</span>
<span style='display:none;'>Copyright All Rights Reserved Ramin Saljoughinejad</span>

In [1]:
import numpy as np

In [2]:
a = np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [3]:
b = np.ones((3,2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [4]:
f = np.ones((2,3), dtype=np.int)
print(f)

[[1 1 1]
 [1 1 1]]


In [5]:
c = np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
d = np.random.random(4)
print(d)

[0.10338147 0.49839845 0.55806832 0.99017671]


In [7]:
e = np.full((2,3),5)
print(e)

[[5 5 5]
 [5 5 5]]


In [8]:
x = np.loadtxt("files/myData.txt", dtype=np.int)
print(x)

[[ 2  3  4  9 12 54 23]
 [ 4  5  9 10 14 55 44]]


In [9]:
np.save("files/myNewData", e)

In [10]:
np.savetxt("files/myNewData.txt", e)