# <span style="color:green;">NumPy 01</span>

<span style="color:red;">The Numpy Array</span>
<span style='display:none;'>Copyright All Rights Reserved Ramin Saljoughinejad</span>

In [1]:
import numpy as np

## Note:
<span style='color:purple;padding-left:25px;'>1- Numpy arrays are fixed in size.</span><br>
<span style='color:purple;padding-left:25px;'>2- numpy arrays are indexed, starting from 0.</span><br>
<span style='color:purple;padding-left:25px;'>3- numpy arrays contain elements of all the same type.</span><br>

### Creating Numpy Arrays

In [2]:
b = np.array([1,2,3,4])
print(b)

[1 2 3 4]


In [3]:
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [4]:
print(b[0])
print(b[1])
print(b[3])

1
2
4


In [5]:
for item in b:
    print(item)

1
2
3
4


In [6]:
for item in c:
    print(item)

[1 2 3]
[4 5 6]


In [7]:
for row in c:
    for elemnt in row:
        print(elemnt)

1
2
3
4
5
6


In [8]:
print("Array b has {x} dimention.".format(x=b.ndim))
print("Array c has {x} dimentions.".format(x=c.ndim))

Array b has 1 dimention.
Array c has 2 dimentions.


In [9]:
print("Array b has the folllowing shape: ",b.shape)
print("Array c has the folllowing shape: ",c.shape)

Array b has the folllowing shape:  (4,)
Array c has the folllowing shape:  (2, 3)


In [10]:
print("Array b has {x} Elements".format(x=b.size))
print("Array c has {x} Elements".format(x=c.size))

Array b has 4 Elements
Array c has 6 Elements


In [11]:
print(type(b))

<class 'numpy.ndarray'>
